---
title: "NFL Draft Project"
author: 'Connor Nickol, email: can2hr@virginia.edu'
date: "4/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyquant)
library(readr)
library(purrr)
```


```{r}
college_stats<-read.csv("college_statistics.csv")
draft<-read.csv("2000-2021 Draft Picks.csv")
```

```{r}
## Going to first look for just wrs

##Filtering out the nas
sum(is.na(college_stats))
college_stats_filter<-college_stats %>% na.omit()
str(college_stats_filter)

##Drop unnecessary columns
college_stats_filter2 <- college_stats_filter %>% select(-c(alt_player_id,school_primary_color,
                                                            school_alt_color,active,all_star))
# Pivoting the data so each season is a row
stats_14_20 <- college_stats_filter2 %>% distinct() %>% group_by(player_id,player_name,season,
                                                  pos_abbr,school, school_abbr) %>% pivot_wider(., names_from = statistic, values_from = value) %>% ungroup() 

```


```{r}
stats_05<-read.csv("player_stats_05.csv")
stats_06<-read.csv("player_stats_06.csv")
stats_07<-read.csv("player_stats_07.csv")
stats_08<-read.csv("player_stats_08.csv")
stats_09<-read.csv("player_stats_09.csv")
stats_10<-read.csv("player_stats_10.csv")
stats_11<-read.csv("player_stats_11.csv")
stats_12<-read.csv("player_stats_12.csv")
stats_13<-read.csv("player_stats_13.csv")
```

```{r}
stats_05_wr<-stats_05 %>% filter(Position == "WR")
stats_06_wr<-stats_06 %>% filter(Position == "WR")
stats_07_wr<-stats_07 %>% filter(Position == "WR")
stats_08_wr<-stats_08 %>% filter(Position == "WR")
stats_09_wr<-stats_09 %>% filter(Position == "WR")
stats_10_wr<-stats_10 %>% filter(Position == "WR")
stats_11_wr<-stats_11 %>% filter(Position == "WR")
stats_12_wr<-stats_12 %>% filter(Position == "WR")
stats_13_wr<-stats_13 %>% filter(Position == "WR")
```

```{r}
stats_5_13_wr<-stats_05_wr %>% full_join(stats_06_wr) %>% 
  full_join(stats_07_wr) %>% full_join(stats_08_wr) %>% 
  full_join(stats_09_wr) %>% full_join(stats_10_wr) %>% 
  full_join(stats_11_wr) %>% full_join(stats_12_wr) %>% 
  full_join(stats_13_wr)

stats_5_13_wr<-stats_5_13_wr %>% select(-c(X))
```

```{r}
## Filtering to just wr and wr stats
stats_14_20_wr<-stats_14_20 %>% filter(pos_abbr == "WR")

stats_14_20_wr<-stats_14_20_wr %>% select(player_id,player_name,pos_abbr,school,
                                          school_abbr,season,`Rushing Touchdowns`,
                                          `Rushing Attempts`,`Rushing Yards`,`Receiving Touchdowns`,
                                          Receptions,`Receiving Yards`)
```

```{r}
## Renaming columns to match older data
stats_14_20_wr<-stats_14_20_wr  %>% rename(Rush.TD = `Rushing Touchdowns`,
                                           Rush.Yard = `Rushing Yards`,
                                           Rush.Att = `Rushing Attempts`,
                                           Rec.Yards = `Receiving Yards`,
                                           Rec.TD = `Receiving Touchdowns`,
                                           Rec = Receptions)
```

```{r}
## Need to replace Null with 0s

str(stats_14_20_wr)

##Convert to characters to replace
stats_14_20_wr <- stats_14_20_wr %>%
  mutate(across(everything(), as.character))

#Replace with 0s
stats_14_20_wr[stats_14_20_wr == "NULL"] <- '0'

#Convert back to numeric columns
stats_14_20_wr <- stats_14_20_wr %>% mutate(Rush.TD = as.numeric(Rush.TD),
                                            Rush.Yard = as.numeric(Rush.Yard),
                                            Rush.Att = as.numeric(Rush.Att),
                                            Rec.TD = as.numeric(Rec.TD),
                                            Rec.Yards = as.numeric(Rec.Yards),
                                            Rec = as.numeric(Rec),
                                            player_id = as.numeric(player_id))
```


```{r}
#Fixing player names and selecting relevant columns
stats_5_13_wr$player_name<-paste(stats_5_13_wr$First.Name,stats_5_13_wr$Last.Name)

stats_5_13_wr_filter<-stats_5_13_wr %>% select(-c(First.Name,Last.Name,Team.Code,
                                                  Class,Pass.Att,
                                                  Pass.Yard,Pass.Comp,Pass.TD,Pass.Int))
```

```{r}
## Joining data together
all_years_wr<-stats_5_13_wr_filter %>% full_join(stats_14_20_wr,by=c("Player.Code"="player_id",
                                                                     "Position" = "pos_abbr",
                                                                      "player_name"="player_name",
                                                                       "Rush.Att"="Rush.Att",
                                                                       "Rush.TD"="Rush.TD",
                                                                       "Rush.Yard"="Rush.Yard",
                                                                       "Rec"="Rec",
                                                                       "Rec.TD"="Rec.TD",
                                                                       "Rec.Yards"="Rec.Yards"))
```

```{r}
#Selecting each receivers best yards season
all_years_wr_f<-all_years_wr %>% group_by(player_name) %>% arrange(desc(Rec.Yards)) %>% slice(1)
```

```{r}
## Only going to use players after 2009 and rounds 1-5

draft_wr <- draft %>% filter(Position=="WR") %>% filter(Year > 2009) %>% filter(Round < 6)

draft_wr_stats <- draft_wr %>% left_join(all_years_wr_f,by=c("Name" = "player_name",
                                                           "Position" = "Position")) %>% 
  select(-c(school, school_abbr, season))

# Going to fill in the NAs by hand
sum(is.na(draft_wr_stats$Rec.Yards))
```

```{r}
#write.csv(draft_wr_stats,"draft_wr_stats.csv",row.names=FALSE)
```

```{r}
## Adding in a conference column
draft_stats<-read.csv("wr_data.csv")

conferences<-read.csv("cbb21.csv")

conferencesf<-conferences %>% select(TEAM,CONF)
```

```{r}
draft_con<-draft_stats %>% left_join(conferencesf,by=c("School"="TEAM"))
```

```{r}
## Making a categorical Power 5 column
p5<-c("ACC","SEC","P12","B10","B12")

draft_con$P_five<-ifelse(draft_con$CONF %in% p5,1,0)
```

```{r}
## Adding in the RAS scores 
ras <- read.csv("wr_ras.csv")

ras<- ras %>% select(-Link)
```


```{r}
draft_model_wr <- draft_con %>% left_join(ras,by=c('Name' = 'Name','School' = 'College', 'Year'))

#write.csv(draft_model_wr,"wr_model_data.csv",row.names=FALSE)

draft_model_wr <- read.csv("wr_model_data.csv")
draft_model_wr<-draft_model_wr %>% na.omit()
```

```{r}
## Looking at the distribution of where guys are picked
ggplot(draft_model_wr, aes(x = Overall)) + geom_histogram() 
```


```{r}
train<-draft_model_wr %>% filter(Year < 2020) %>% mutate(P_five=as.factor(P_five))
test<-draft_model_wr %>% filter(Year > 2019) %>% mutate(P_five=as.factor(P_five))
```

```{r}
result<-lm(Overall~Rec.Yards+Rec.TD+Rec+RAS+P_five,data=train)
test$predict<-round(predict(result,newdata = test))
test_mse_ln<-mean((test$Overall-test$predict)^2)
test_mse_ln

summary(result)
```

```{r}
yhat<-result$fitted.values 
res<-result$residuals
Data<-data.frame(train,yhat,res)

ggplot(Data, aes(x=yhat,y=res))+
  geom_point()+
  geom_hline(yintercept=0, color="red")+
  labs(x="Fitted y",
       y="Residuals",
       title="Residual Plot")
```

```{r}
qqnorm(res)
qqline(res, col="red")
```

```{r}
ggplot(draft_model_wr, aes(x = Overall, y = RAS)) + geom_point() + geom_smooth(method = 'lm', se = FALSE)
```

```{r}
ras_result <- lm(Overall~RAS, data = draft_model_wr)
yhat<-ras_result$fitted.values 
res<-ras_result$residuals
##add to data frame
Data<-data.frame(draft_model_wr,yhat,res)

ggplot(Data, aes(x=yhat,y=res))+
  geom_point()+
  geom_hline(yintercept=0, color="red")+
  labs(x="Fitted y",
       y="Residuals",
       title="Residual Plot")
```

```{r}
wr_scale <- draft_model_wr %>% mutate_at(c('RAS','Rec.Yards','Rec.TD'),~(scale(.)%>% as.vector))
wr_scale <- wr_scale %>% mutate(avg_stats = (RAS + Rec.Yards + Rec.TD)/3)
```

```{r}
ggplot(wr_scale, aes(x = Overall, y = avg_stats)) + geom_point() + geom_smooth(method = 'lm', se = FALSE)
```













